# Generated by Django 3.0.6 on 2025-10-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prometheusyml_node',
            field=models.CharField(default=2, max_length=5000),
            preserve_default=False,
        ),
    ]
