# Generated by Django 3.0.6 on 2025-10-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0002_student_prometheusyml_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='prometheusyml_node',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
