# Generated by Django 3.0.6 on 2025-10-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0003_auto_20251027_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='prometheusyml_node',
            new_name='job_name',
        ),
        migrations.AddField(
            model_name='student',
            name='selected_targets_str',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
