# Generated by Django 3.0.6 on 2025-11-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0004_auto_20251027_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='custom_config_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='custom_selected_targets_str',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
