# Generated by Django 3.0.6 on 2025-11-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0005_auto_20251106_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(max_length=32),
        ),
    ]
